/**
* Get all movies from movies API
* */
export const getAllMovies = async() => {
  // Use mock data in dev
  if(process.env.NODE_ENV === 'development') {
      return new Promise((resole) => {
        return resole([
          {
            "id": "34",
            "title": "Paul, Apostle of Christ",
            "year": "2018",
            "genres": [
              "Drama"
            ],
            "ratings": [
              8,
              1,
              8,
              1,
              9,
              10,
              6,
              4,
              8,
              1,
              10,
              4,
              8,
              6,
              8,
              5,
              8,
              9,
              2,
              9,
              7,
              5,
              10,
              7,
              5,
              2,
              2,
              4,
              2,
              9
            ],
            "poster": "MV5BMWRkYTQ4NzctMDAwYS00NmE3LWI5NzUtMTMzNTQ0MDgwOWI1XkEyXkFqcGdeQXVyODQyOTY2OTA@._V1_SY500_CR0,0,337,500_AL_.jpg",
            "contentRating": "PG-13",
            "duration": "",
            "releaseDate": "2018-03-28",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "PAUL, APOSTLE OF CHRIST is the story of two men. Luke, as a friend and physician, risks his life when he ventures into the city of Rome to visit Paul, who is held captive in Nero's darkest, bleakest prison cell. . But Nero is determined to rid Rome of Christians, and does not flinch from executing them in the grisliest ways possible. Before Paul's death sentence can be enacted, Luke resolves to write another book, one that details the beginnings of \"The Way\" and the birth of what will come to be known as the church. Bound in chains, Paul's struggle is internal. He has survived so much-floggings, shipwreck, starvation, stoning, hunger and thirst, cold and exposure-yet as he waits for his appointment with death, he is haunted by the shadows of his past misdeeds. Alone in the dark, he wonders if he has been forgotten . . . and if he has the strength to finish well. Two men struggle against a determined emperor and the frailties of the human spirit in order to live out the Gospel of Jesus...",
            "actors": [
              "James Faulkner",
              "Jim Caviezel",
              "Joanne Whalley"
            ],
            "imdbRating": "",
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMWRkYTQ4NzctMDAwYS00NmE3LWI5NzUtMTMzNTQ0MDgwOWI1XkEyXkFqcGdeQXVyODQyOTY2OTA@._V1_SY500_CR0,0,337,500_AL_.jpg"
          },
          {
            "id": "35",
            "title": "Midnight Sun",
            "year": "2018",
            "genres": [
              "Drama",
              "Romance"
            ],
            "ratings": [
              6,
              4,
              8,
              2,
              6,
              9,
              6,
              1,
              10,
              8,
              3,
              2,
              4,
              10,
              4,
              10,
              8,
              5,
              4,
              7,
              4,
              8,
              1,
              5,
              5,
              1,
              9,
              9,
              9,
              10
            ],
            "poster": "MV5BMjg0NjU1MjgyNF5BMl5BanBnXkFtZTgwNzc5NjYyNDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
            "contentRating": "PG-13",
            "duration": "",
            "releaseDate": "2018-03-30",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "Based on the Japanese film, Midnight Sun centers on Katie, a 17-year-old sheltered since childhood and confined to her house during the day by a rare disease that makes even the smallest amount of sunlight deadly. Fate intervenes when she meets Charlie and they embark on a summer romance.",
            "actors": [
              "Bella Thorne",
              "Patrick Schwarzenegger",
              "Rob Riggle"
            ],
            "imdbRating": "",
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjg0NjU1MjgyNF5BMl5BanBnXkFtZTgwNzc5NjYyNDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
          },
          {
            "id": "36",
            "title": "Hichki",
            "year": "2018",
            "genres": [
              "Drama"
            ],
            "ratings": [
              9,
              5,
              10,
              7,
              5,
              8,
              1,
              9,
              8,
              5,
              8,
              6,
              3,
              5,
              4,
              5,
              3,
              2,
              8,
              10,
              3,
              5,
              7,
              5,
              6,
              10,
              6,
              9,
              2,
              10
            ],
            "poster": "MV5BMDNkZTVjYWMtZGJjNS00YTM5LWI1YmMtYmY0ZDFlOWNlZjFmXkEyXkFqcGdeQXVyMTkzOTcxOTg@._V1_SY500_CR0,0,357,500_AL_.jpg",
            "contentRating": "",
            "duration": "PT106M",
            "releaseDate": "2018-03-23",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "Hichki is a story about a woman who turns her most daunting weakness into her biggest strength. Naina Mathur (Rani Mukerji) is an aspiring teacher who suffers from Tourette Syndrome. After several interviews and numerous rejections, she lands her dream job as a full-time teacher in one of the most elite schools in the city. However, she soon realises that the class she has been assigned comprises of defiant and impish students who can't seem to keep out of trouble. Despite a few initial hiccups, Naina must do whatever she can to ensure that her students realise their true potential, and defy all the odds against them.                Written by\nOfficial Source",
            "actors": [
              "Rani Mukerji",
              "Ivan Rodrigues",
              "Asif Basra"
            ],
            "imdbRating": "",
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDNkZTVjYWMtZGJjNS00YTM5LWI1YmMtYmY0ZDFlOWNlZjFmXkEyXkFqcGdeQXVyMTkzOTcxOTg@._V1_SY500_CR0,0,357,500_AL_.jpg"
          },
          {
            "id": "37",
            "title": "Final Portrait",
            "year": "2017",
            "genres": [
              "Biography",
              "Comedy",
              "Drama"
            ],
            "ratings": [
              9,
              10,
              1,
              4,
              6,
              4,
              5,
              2,
              5,
              8,
              1,
              9,
              6,
              1,
              7,
              5,
              7,
              9,
              3,
              6,
              2,
              4,
              10,
              7,
              4,
              10,
              7,
              3,
              7,
              5
            ],
            "poster": "MV5BMTUwMDc0NTU1MV5BMl5BanBnXkFtZTgwMTcxOTk3MjI@._V1_SY500_CR0,0,337,500_AL_.jpg",
            "contentRating": "R",
            "duration": "PT90M",
            "releaseDate": "2017-08-18",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "In 1964, while on a short trip to Paris, the American writer and art-lover James Lord (Armie Hammer) is asked by his friend, the world-renowned artist Alberto Giacometti (Geoffrey Rush), to sit for a portrait. The process, Giacometti assures Lord, will take only a few days. Flattered and intrigued, Lord agrees. So begins not only the story of an offbeat friendship, but, seen through the eyes of Lord, an insight into the beauty, frustration, profundity and, at times, downright chaos of the artistic process. FINAL PORTRAIT is a portrait of a genius, and of a friendship between two men who are utterly different, yet increasingly bonded through a single, ever-evolving act of creativity. It is a film which shines a light on the artistic process itself, by turns exhilarating, exasperating and bewildering, questioning whether the gift of a great artist is a blessing or a curse.",
            "actors": [
              "Armie Hammer",
              "Cl\u00e9mence Po\u00e9sy",
              "Tony Shalhoub"
            ],
            "imdbRating": 6.4,
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwMDc0NTU1MV5BMl5BanBnXkFtZTgwMTcxOTk3MjI@._V1_SY500_CR0,0,337,500_AL_.jpg"
          },
          {
            "id": "38",
            "title": "Izzy Gets the F*ck Across Town",
            "year": "2017",
            "genres": [
              "Comedy",
              "Drama"
            ],
            "ratings": [
              9,
              6,
              1,
              4,
              5,
              10,
              5,
              8,
              2,
              5,
              7,
              5,
              5,
              9,
              10,
              1,
              8,
              6,
              2,
              4,
              9,
              2,
              3,
              8,
              7,
              7,
              2,
              6,
              9,
              1
            ],
            "poster": "MV5BYTY2OTdlY2YtMWVlYy00ZjU4LWE2ODEtZWIxMDJjYTE0MjkwXkEyXkFqcGdeQXVyNTMzNzIxODA@._V1_SY480_SX317_AL_.jpg",
            "contentRating": "",
            "duration": "PT86M",
            "releaseDate": "2018-03",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "Broke, job hopping, indie musician, Izzy has just discovered that her ex-boyfriend- her soulmate!- got engaged to her ex-best friend, and their party happens to be tonight. Enraged and desperate, Izzy embarks on a quest to charge across Los Angeles and break that up in order to fulfill what she believes to be her destiny - before it's too late.",
            "actors": [
              "Haley Joel Osment",
              "Mackenzie Davis",
              "Alia Shawkat"
            ],
            "imdbRating": 8.4,
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYTY2OTdlY2YtMWVlYy00ZjU4LWE2ODEtZWIxMDJjYTE0MjkwXkEyXkFqcGdeQXVyNTMzNzIxODA@._V1_SY480_SX317_AL_.jpg"
          },
          {
            "id": "39",
            "title": "I Kill Giants",
            "year": "2017",
            "genres": [
              "Drama",
              "Fantasy",
              "Thriller"
            ],
            "ratings": [
              10,
              4,
              4,
              1,
              5,
              6,
              7,
              1,
              3,
              2,
              6,
              5,
              9,
              5,
              3,
              3,
              1,
              5,
              4,
              3,
              3,
              9,
              8,
              4,
              1,
              10,
              2,
              6,
              10,
              5
            ],
            "poster": "MV5BMjM1MTc3ODcwMV5BMl5BanBnXkFtZTgwNTU2MjA4NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
            "contentRating": "11",
            "duration": "PT104M",
            "releaseDate": "2018-03-23",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "Barbara Thorson struggles through life by escaping into a fantasy life of magic and monsters.",
            "actors": [
              "Zoe Saldana",
              "Imogen Poots",
              "Jennifer Ehle"
            ],
            "imdbRating": 7.2,
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjM1MTc3ODcwMV5BMl5BanBnXkFtZTgwNTU2MjA4NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
          },
          {
            "id": "40",
            "title": "Les fant\u00f4mes d'Isma\u00ebl",
            "year": "2017",
            "genres": [
              "Drama",
              "Romance",
              "Thriller"
            ],
            "ratings": [
              1,
              1,
              9,
              7,
              9,
              4,
              8,
              1,
              5,
              2,
              7,
              7,
              10,
              8,
              4,
              3,
              10,
              2,
              6,
              9,
              1,
              1,
              1,
              6,
              3,
              7,
              1,
              9,
              5,
              7
            ],
            "poster": "MV5BMzdkMTQ1NzItOTFkNC00NGRiLTg2ZGQtNDkzNjU0YjJjYTFkXkEyXkFqcGdeQXVyNTU5NTk3MDA@._V1_SY384_CR0,0,286,384_AL_.jpg",
            "contentRating": "R",
            "duration": "PT114M",
            "releaseDate": "2017-05-17",
            "averageRating": 0,
            "originalTitle": "",
            "storyline": "The film tells the tale of a widowed film director who is in the middle of making a film about an atypical diplomat inspired by his brother. While he has started a new life with Sylvia, he still mourns the death of a former lover, Carlotta, who passed away 20 years earlier; then Carlotta returns from the dead, causing Sylvia to run away                Written by\nDick Nolan",
            "actors": [
              "Mathieu Amalric",
              "Marion Cotillard",
              "Charlotte Gainsbourg"
            ],
            "imdbRating": 5.8,
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzdkMTQ1NzItOTFkNC00NGRiLTg2ZGQtNDkzNjU0YjJjYTFkXkEyXkFqcGdeQXVyNTU5NTk3MDA@._V1_SY384_CR0,0,286,384_AL_.jpg"
          },
          {
            "id": "41",
            "title": "V\u00e5r ving\u00e5rd i Bourgogne",
            "year": "2017",
            "genres": [
              "Comedy",
              "Drama"
            ],
            "ratings": [
              9,
              2,
              3,
              10,
              9,
              3,
              4,
              6,
              6,
              6,
              3,
              7,
              9,
              8,
              3,
              9,
              9,
              10,
              7,
              9,
              1,
              10,
              9,
              4,
              5,
              7,
              7,
              10,
              8,
              2
            ],
            "poster": "MV5BMmI2MjgyYzUtZTEzMy00M2IwLWJjMGQtNDgyODBjNWVkODNmXkEyXkFqcGdeQXVyNDU0NjMyNTQ@._V1_SY500_CR0,0,337,500_AL_.jpg",
            "contentRating": "Btl",
            "duration": "PT113M",
            "releaseDate": "2017-09-22",
            "averageRating": 0,
            "originalTitle": "Ce qui nous lie",
            "storyline": "After a 10 year absence, Jean returns to his hometown when his father falls ill. Reuniting with his sister Juliette and his brother J\u00e9r\u00e9mie, they have to re-build their relationship and trust as a family again.",
            "actors": [
              "Pio Marma\u00ef",
              "Ana Girardot",
              "Fran\u00e7ois Civil"
            ],
            "imdbRating": 7.0,
            "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMmI2MjgyYzUtZTEzMy00M2IwLWJjMGQtNDgyODBjNWVkODNmXkEyXkFqcGdeQXVyNDU0NjMyNTQ@._V1_SY500_CR0,0,337,500_AL_.jpg"
          },
        ])
      })
  }

  // Consume PHP sever in Production
  return fetch('/server/movies.php')
      .then(response => {
        if (response.ok) {
          return response.json();
        }
        throw new Error(response.statusText);
      })
}
